### ISSUE TITLE
Seg Fault for Simple Network

### ISSUE THREAD

**Issue by chelseas** [guykatzz/Marabou#127]
I pulled the main branch with latest commit: 54ae6c26dadcd015548a94adf78f763d2446bd18
Using maraboupy
The network I am testing is just input = [[x]], W = [[1, 1, 1, 1]], output = [[x, x, x, x]]
I input a .pb and the equation list that is generated is:
```
>>> [e.addendList for e in network.equList]
[[(1.0, 0), (-1, 1)], [(1.0, 0), (-1, 2)], [(1.0, 0), (-1, 3)], [(1.0, 0), (-1, 4)]]
>>> [e.scalar for e in network.equList]
[0.0, 0.0, 0.0, 0.0]
```
So as you can see, very simple. 

I set the input to be between 0 and 1 and test if the output is less than 4.
```
network.setLowerBound(0, 0.) 
network.setUpperBound(0, 1.)
for i in range(4):
	network.setUpperBound(output_vars[0][i], 4.)
```
After which:
```
>>> network.lowerBounds
{0: 0.0}
>>> network.upperBounds
{0: 1.0, 1: 4.0, 2: 4.0, 3: 4.0, 4: 4.0}
```

Which should return SAT. However, instead I get a segfault. The solver output is attached.

[marabou_issue_2_14.txt](https://github.com/guykatzz/Marabou/files/2866908/marabou_issue_2_14.txt)

**Comment by yuvaljacoby** [comment]
Hey @chelseas 
Cloned the branch and seems the problem was fixed.
Can we close the issue?
