### ISSUE TITLE
Setting --verbosity=0 has no impact in the single-solver mode

### ISSUE THREAD

**Issue by ahmed-irfan** [guykatzz/Marabou#155]
the single solver still prints a lot of statistics, whereas the help says that the solver should not print anything

**Comment by anwu1219** [comment]
Fixed in this commit: https://github.com/guykatzz/Marabou/commit/9180c153d71cdbe6305230da086f21e3f90a9fad

**Comment by ahmed-irfan** [comment]
confirmed the fix....

closing the issue
