### ISSUE TITLE
make on Mac OS: error: use of undeclared identifier 'sched_getcpu'

### ISSUE THREAD

**Issue by tomerarnon** [guykatzz/Marabou#170]
https://github.com/guykatzz/Marabou/blob/a11d6a887881ab46f8222af57d82a3228e212ebd/src/engine/DnCManager.cpp#L40

Commenting out the line above allows the build to proceed.

**Comment by anwu1219** [comment]
Hi, I created this PR to address this issue. Please let me know if it works. 
https://github.com/guykatzz/Marabou/pull/177

**Comment by tomerarnon** [comment]
Hey @anwu1219, your PR compiles just fine for me. 
I didn't try to run the DnC solver to make sure it prints though.

**Comment by anwu1219** [comment]
Closing the issue after merging https://github.com/guykatzz/Marabou/pull/177
