### ISSUE TITLE
Training dataset for ACAS Xu DNNs

### ISSUE THREAD

**Issue by rnbguy** [guykatzz/Marabou#173]
I can find the ACAS Xu neural networks in the "resources" directory. But is there any way to make the training set public?

**Comment by kjulian3** [comment]
Unfortunately the training set can't be shared publicly as it's FAA proprietary data. We got special permission to release these prototype networks, but we aren't able to release the training data.

Recently, I've been working on a simple open-source system inspired by ACAS Xu that is available at https://github.com/sisl/HorizontalCAS. This is not the ACAS Xu system, but it uses the same ideas to generate training data and train a neural network. This is still a work in progress, but if this is useful for you, feel free to us it.

**Comment by rnbguy** [comment]
@kjulian3 actually you're the person, I wanted to ask. It is unfortunate that the ACAS Xu score table is proprietary. Maybe I can do something similar to [ART paper](https://arxiv.org/abs/1907.10662)(5.2) to generate a reasonable training set.

Also, thanks for HorizontalCAS. It looks an interesting project. I will definitely look into that.
