### ISSUE TITLE
maraboupy "cannot import name 'MarabouCore'"

### ISSUE THREAD

**Issue by tomerarnon** [guykatzz/Marabou#174]
On MacOS, when trying to run `Example Notebook.ipynb` in the maraboupy examples:
```python
from maraboupy import Marabou
```
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-10-4bdfef60576a> in <module>()
> ----> 1 from maraboupy import Marabou
> 
> ~/Documents/Stanford/Marabou/maraboupy/Marabou.py in <module>()
>      18 
>      19 #Marabou File
> ---> 20 from .MarabouNetworkNNet import *
>      21 from .MarabouNetworkTF import *
>      22 
> 
> ~/Documents/Stanford/Marabou/maraboupy/MarabouNetworkNNet.py in <module>()
>      17 '''
>      18 
> ---> 19 from .MarabouUtils import *
>      20 from maraboupy import MarabouNetwork
>      21 import numpy as np
> 
> ~/Documents/Stanford/Marabou/maraboupy/MarabouUtils.py in <module>()
>      17 '''
>      18 
> ---> 19 from maraboupy import MarabouCore
>      20 
>      21 class Equation:
> 
> ImportError: cannot import name 'MarabouCore'

This is after running `make` so the .so file (`MarabouCore.cpython-36m-darwin.so`) exists. I'm not sure how to debug this further, so help is appreciated!

**Comment by AleksandarZeljic** [comment]
Did you export  the Python and Jupyter paths?

**Comment by tomerarnon** [comment]
@AleksandarZeljic I ran the line in the first cell that appends to `sys.path`, with the path to the Marabou directory, so I assume so.

**Comment by AleksandarZeljic** [comment]
Hm, yeah, you understood me correctly the first time around. Maybe we can sit together and try to figure it out, it has definitely been touchy to make it work.

**Comment by tomerarnon** [comment]
Turns out it was a python version issue. I was running 3.5.4 and the compilation path was for 3.6. Thanks @yuvaljacoby for resolving!

**Comment by yuvaljacoby** [comment]
@tomerarnon we did some changes in the ipynb to make it work.
can you push that?

For future debugging - make sure the python version you run (import sys; print(sys.version_info)) is the same as the MarabouCore.cpython-VERSION_NAME.so

**Comment by tomerarnon** [comment]
@yuvaljacoby there were two typos in Example.ipynb as I recall:

1. `timeit, vals1, stats1 = net1.solve()` we deleted `timeit`.

2. Later in the notebook, the variable `net3` is not defined, but we didn't bother to fix that once we saw that everything else was behaving correctly. 

Should I PR getting rid of `timeit`? I'm not sure what the original intent behind `net3` was.
