### ISSUE TITLE
Typo in the example?

### ISSUE THREAD

**Issue by zhanghongce** [guykatzz/Marabou#201]
https://github.com/guykatzz/Marabou/blob/29899653d2043955fa29548112dbd6397380cf42/maraboupy/examples/MarabouCoreExample.py#L32

Is it a typo since there are no other places with `x3f` and `x3b`? 
Thanks!

**Comment by zhanghongce** [comment]
And also, I feel that the line:
https://github.com/guykatzz/Marabou/blob/29899653d2043955fa29548112dbd6397380cf42/maraboupy/examples/MarabouCoreExample.py#L87
should be replaced with
```vars1, stats1 = MarabouCore.solve(inputQuery, MarabouCore.Options(), "")```

**Comment by yuvaljacoby** [comment]
Thank you for the comments.
Regarding the first issue, thank you, that should be x1f = Relu(x1b), will fix it.

Regarding the second issue, this function actually calls maraboupy/MarabouCore.cpp::solve (line 108) which don't get an Options object. 
Currently we don't support changing options through the python API. You can change directly the config file (src/configuration) if needed

**Comment by yuvaljacoby** [comment]
Apparently I was not aware of a recent API change that the second issue was related to. fixed it here #203
