### ISSUE TITLE
Test Fail -- Bug in setting upper bound of auxiliary variables

### ISSUE THREAD

**Issue by typerSniper** [guykatzz/Marabou#206]
Test Description:
	

    model.nnet: 
		The model has two inputs (x0, x1), two outputs(y0, y1) and 1 hidden layer(RELU) of size 4 (ws_1_0, ws_1_1, ws_1_2, ws_1_3).  
		One of the valid assignments to these variables is (x0 = 2, x1 = 1.5) & (y0 = 1.5, y1 = 3.0) & (ws_1_0 = 1.5, ws_1_1 = 0.5,  ws_1_2 = 3, ws_1_3 = -6).  
		This can be corroborated by calling the solver on prop_1.txt and printing result of a forward pass on the network.  
		But the solver returns UNSAT on prop_2.txt. The only additional constraint in this file is ws_1_1 >= 0.5, which is consistent with the previous satisfying assignment.  
			
	Command used to run: ./{PATH_TO_MARABOU_MASTER} bug-report/model.nnet bug-report/prop_1.txt

Potential Bug:
	
		src/engine/ReluConstraint.cpp:727 (in function addAuxiliaryEquations). 
                 inputQuery.setUpperBound( _aux, -_lowerBounds[_b] );

Explanation:

	Let me refer to the weighted sum variables (ws_1_0, ws_1_1, ws_1_2, ws_1_3) as (2, 3, 4, 5) and the corresponding RELU outputs be (6, 7, 8, 9).  
	Let lb_2 be the lower bound of 2. 
	The Preprocessor::preprocess method calls addPlAuxiliaryEquations. The purpose being to add the piecewise linear constraints (6 >= 2, 7 >= 3 ...) to the solver. Since we want to specify these constraints using equalities, we introduce auxiliary variables (12, 13, 14, 15) and add constraints like: 6 - 2 - 12 = 0.  
	This is accompanied by setting lower and upper bounds for 12. The lower bound for 12 is indeed 0 since 6 >= 2. But the upper bound is set to be -(lb_2), which I suspect is not correct. 
	6 - 2 - 12 = 0 and 6>=2 and 12 >=0 does not imply 12 <= -lb_2. Counter-example : (6 = 2, 12= 0.0, lb_2 = 0.5). 

[bug-report.zip](https://github.com/guykatzz/Marabou/files/3889031/bug-report.zip)

**Comment by typerSniper** [comment]
My suspicion is reinforced by the fact that MaxConstraint::addAuxiliaryEquations in src/engine/MaxConstraint.cpp does not set this upper bound for aux

**Comment by guykatzz** [comment]
Thanks for the report and for identifying the problematic lines in the code. I've pushed a fix, please try again now.

**Comment by typerSniper** [comment]
This works. Thanks
